import Navbar from '@/components/layout/navbar';
import '../styles/globals.css';
//import { Inter } from 'next/font/google';
import Footer from '@/components/layout/footer';

//const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Angels',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <Navbar />
                {children}
                <Footer />
            </body>
        </html>
    );
}
